### ISSUE TITLE
Installing causes this error

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_analysis_expression#102]
We should probably report this on `tripal_chado` if we the our install function needs to run this function.

```
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_cv_defaults" does not exist                                        [error]
LINE 1: DELETE FROM tripal_cv_defaults 
                    ^ in /home/vagrant/code/includes/database/database.inc:2227
Stack trace:
#0 /home/vagrant/code/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /home/vagrant/code/includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /home/vagrant/code/includes/database/query.inc(858): DatabaseConnection_pgsql->query('DELETE FROM {tr...', Array, Array)
#3 /home/vagrant/code/sites/all/modules/tripal/tripal_chado/api/modules/tripal_chado.cv.api.inc(1578): DeleteQuery->execute()
#4 /home/vagrant/code/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/tripal_biomaterial.install(42):
tripal_set_default_cv('biomaterialprop', 'type_id', 'biomaterial_pro...')
#5 /home/vagrant/code/includes/module.inc(926): tripal_biomaterial_install()
#6 /home/vagrant/code/includes/module.inc(494): module_invoke('tripal_biomater...', 'install')
#7 /home/vagrant/.composer/vendor/drush/drush/commands/core/drupal/environment_7.inc(143): module_enable(Array)
#8 /home/vagrant/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1122): drush_module_enable(Array)
#9 /home/vagrant/.composer/vendor/drush/drush/includes/command.inc(361): drush_pm_enable('tripal_analysis...')
#10 /home/vagrant/.composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
#11 /home/vagrant/.composer/vendor/drush/drush/includes/command.inc(180): drush_command('tripal_analysis...')
#12 /home/vagrant/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
#13 /home/vagrant/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#14 /home/vagrant/.composer/vendor/drush/drush/drush.php(11): drush_main()
#15 {main}
```

**Comment by bradfordcondon** [comment]
this particular error is a tripal 3 bug i believe: `tripal_cv_defaults` is used in the tripal 3 tripal_chado but, it uses the tripal_cv_defaults table which isnt defined in tripal_3 (but was defined in legacy).

https://github.com/tripal/tripal/issues/200

**Comment by bradfordcondon** [comment]
`tripal_cv_defaults` appears to be pointless and deprecated, lets just remove the call
